name: "Conftest"
description: "Run conftest (conftest.dev) to enforce OPA policies"
author: "muncus"

inputs:
  output:
    description: "output format"
    default: "github"
  files:
    description: "files/directories to check against policies"
    required: true
  policy:
    description: "location of Rego policies to be loaded"
    default:  "policy"
  extra_args:
    description: "extra arguments to pass to conftest."
    default: "--all-namespaces"

runs:
  using: 'docker'
  image: 'docker://openpolicyagent/conftest:latest'
  args:
    - "test"
    - "--output"
    - "${{ inputs.output }}"
    - "--policy"
    - "${{ inputs.policy }}"
    - "${{ inputs.extra_args }}"
    - "--"
    - "${{ inputs.files }}"
